[build]
  command = "npm run build"       # oder dein Build-Befehl
  publish = "dist"                # Ordner, den Vite baut, z.B. "dist" oder "build"
  functions = "netlify/functions" # sagt Netlify, wo die Functions liegen
